<table align="left">
  <td>
    <a href="https://colab.research.google.com/github/salamhha/handson-ml3/blob/main/practice/Chapter09.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>
  </td>
</table>

In [2]:
# K-means
from sklearn.cluster import KMeans
from sklearn.datasets import make_blobs

k = 5
X, y = make_blobs(n_samples=1500, n_features=2,
                  centers=k, random_state=42)
kmeans = KMeans(n_clusters=k, random_state=42)
y_pred = kmeans.fit_predict(X)

In [3]:
y_pred

array([4, 0, 2, ..., 4, 0, 1], dtype=int32)

In [4]:
kmeans.cluster_centers_

array([[ 2.07564643,  4.16862733],
       [-6.85406294, -6.7780619 ],
       [-8.90992726,  7.38564553],
       [-2.51326868,  8.99855257],
       [ 4.7933247 ,  1.99328561]])

In [5]:
import numpy as np
X_new = np.array([[0, 2], [3, 2], [-3, 3], [-3, 2.5]])
kmeans.predict(X_new)

array([0, 4, 0, 0], dtype=int32)

In [6]:
kmeans.transform(X_new).round(2)

array([[ 3.  , 11.14, 10.41,  7.44,  4.79],
       [ 2.36, 13.2 , 13.07,  8.91,  1.79],
       [ 5.21, 10.51,  7.36,  6.02,  7.86],
       [ 5.34, 10.05,  7.67,  6.52,  7.81]])